#!/bin/bash
#
# This builds and runs a microservice.
#

export SERVICE=secore-template

set -e

. build/version.properties

# Only use --pull option of docker build if we have internet connectivity
#   (otherwise docker build will fail)
if ping -q -c1 inomial.io >/dev/null 2>&1; then
  online_docker_args="--pull"
else
  online_docker_args=""
fi

cp build/libs/$SERVICE-$version-all.jar docker
pushd docker
docker build $online_docker_args -t inomial.io/$SERVICE --build-arg version=$version .
popd
