#!/bin/bash
#
# This builds and runs a microservice.
#

set -e
set -u

cd "$(dirname "$0")"

. build/version.properties

# if running on Jenkins or if .git directory exists then determine the git origin and commit reference
if [ "${BUILD_URL:-}" ] || [ -d .git ]; then
  VCS_URL=$(git config --get remote.origin.url)
  VCS_REF=$(git rev-parse HEAD)
else
  VCS_URL='Not a git repository'
  VCS_REF=''
fi

BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
BUILD_VERSION=$(<build.version)

# abort if running on Jenkins (BUILD_URL is set) but BUILD_VERSION is still set to DEV
if [ "${BUILD_URL:-}" ]; then
  if [ "$BUILD_VERSION" = DEV ]; then
    echo "BUILD_VERSION=$BUILD_VERSION not permitted on a Jenkins build." >&2
    exit 1
  fi
fi

# Only use --pull option of docker build if we have internet connectivity
#   (otherwise docker build will fail)
if ping -q -c1 inomial.io >/dev/null 2>&1; then
  online_docker_args="--pull"
else
  online_docker_args=""
fi

cp build/libs/$project-$version.jar docker
cd docker
if [ -f ../build/libs/$project-$version-grow.jar ]; then
  rm -rf GROW
  jar xf ../build/libs/$project-$version-grow.jar GROW
  chmod +x GROW/com.inomial/grow/bin/grow.sh
else
  # Keep Dockerfile happy
  mkdir -p GROW
fi
docker build \
        $online_docker_args \
        -t inomial.io/$project \
        --build-arg version=$version \
        --build-arg project=$project \
        --build-arg description="$description" \
        --build-arg BUILD_DATE="$BUILD_DATE" \
        --build-arg BUILD_VERSION="$BUILD_VERSION" \
        --build-arg VCS_URL="$VCS_URL" \
        --build-arg VCS_REF="$VCS_REF" \
        .
