#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

. build/version.properties

versionNumber=$(<build.version)

docker tag "inomial.io/${project}" "inomial.io/${project}:${versionNumber}"

if [ "${1:-}" = archive ]; then
  # archive image
  docker save "inomial.io/${project}:${versionNumber}" | gzip > "${project}-${versionNumber}.tar.gz"
else
  # push image
  docker push "inomial.io/${project}:${versionNumber}"
  docker push "inomial.io/${project}:latest"
fi
